### ISSUE TITLE
RS is U+001E, US is U+001F

### ISSUE THREAD

**Issue by cabo** [oldgrognard/ccsv-id#1]

**Comment by oldgrognard** [comment]
Can you help me better understand why the FS (U+001C) should be used instead of the US (U+001E)? I understand that the four control characters (FS, GS, RS, and US) are intentionally vague while maintaining a firm hierarchy.  

I relied on Lammert Bies' ASCII history lesson in his [ASCII character map article](https://www.lammertbies.nl/comm/info/ascii-characters) to provide the common definitions of the control characters in question.  The definitions there seem to suggest that the unit separator (US) should be used to delimit the fields, and the record separator (RS) should be used to separate the records of a table.  

I did find an example that supports the use of the FS to separate fields.  That was the ANSI/NIST-ITL Standard, which defined its "Traditional Encoding." to use the FS to separate logical records.  They also needed all four separators to manage their data.

If we adopted the FS to separate the fields in the data, wouldn't that confusingly invert the hierarchy?

In the case of the CCSV, we only need two of the unit separator control characters.  If using the popular definitions of the separators, there is no need to use a file separator since the CCSV itself is a file.  The group separator (GS) also seems unnecessary since we work exclusively with rectangular data.

-edit: Oh, I see there is an error in the rules section that needs to be corrected regarding the separators.

I'm interested to hear where my thinking has missed the mark.

**Comment by cabo** [comment]
You are completely right about using RS for the lines and US for the fields.  Sorry, I did this from memory, and apparently misremembered...
