### ISSUE TITLE
Don't use BOM

### ISSUE THREAD

**Issue by cabo** [oldgrognard/ccsv-id#2]

**Comment by oldgrognard** [comment]
Thanks for your input. I've been vacillating between including this and not including it. Guidance from things like [rfc6657/](https://datatracker.ietf.org/doc/rfc6657/) and [proposed update for Unicode v16](https://www.unicode.org/L2/L2021/21038-bom-guidance.pdf) can seem contradictory or at least indeterminate. In the cases where I've been using the CCSV format, I've never used it.  From a practical standpoint, I agree that it makes sense to remove it altogether since it may cause issues with software running in US-ASCII mode that sees a file starting with something that it doesn't understand.
